# Configuração de Livros
# Formato: nome_completo|abreviação|código_numerico
# 
# Novo Testamento

# Evangelhos
mateus|Mt|40
marcos|Mc|41
lucas|Lc|42
joão|Jo|43

# História
atos|At|44

# Cartas Paulinas
romanos|Rm|45
1coríntios|1Co|46
2coríntios|2Co|47
gálatas|Gl|48
efésios|Ef|49
filipenses|Fp|50
colossenses|Cl|51
1tessalonicenses|1Ts|52
2tessalonicenses|2Ts|53
1timóteo|1Tm|54
2timóteo|2Tm|55
tito|Tt|56
filemom|Fm|57

# Cartas Gerais
hebreus|Hb|58
tiago|Tg|59
1pedro|1Pe|60
2pedro|2Pe|61
1joão|1Jo|62
2joão|2Jo|63
3joão|3Jo|64
judas|Jd|65

# Profético
apocalipse|Ap|66
